---
title: "The Making of the World of Espionage: A Brief Political Economic Analysis of the Popularization of Ibn-e-Safi’s *jasusi* Novels in 1950s Karachi"
author: |
  Shuyan (Michael) Huang
fontsize: 12pt
output: pdf_document
bibliography: /Users/michaelhuang/Dropbox/University of Chicago/2023FALL_PhD_application/writing sample/bibli.bib
---

```{r setup, include=FALSE, echo=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)
tinytex::tlmgr_install("pdfcrop")
library(tidyverse)
library(reshape2)
library(readxl)
library(huxtable)
library(knitr) 
library(plm)
```

######################################################################
######### PLEASE REACH OUT TO ME FOR THE DATASETS ####################
#####################################################################

# FIGURE 1. 
```{r echo=FALSE, message=FALSE, warning=FALSE}
year <- c(1948,1949,1950,1951,1952,1953,1954,1955,1956,1957,1958,1959,1960)
no_film <- c(1,6,13,8,6,10,7,19,32,27,33,38,40)
df <- tibble(year,no_film)
ggplot(df,
       aes(x=year,y=no_film))+
  geom_point()+
  geom_line()+
  labs(
    title = "Figure 1. Number of Films Released in Karachi",
    x = "Year",
    y = "Number of Films",
    caption = "Source: Pakistan Film Magazine: https://pakmag.net/film/"
  )+
  theme(plot.title = element_text( size = 11))
```

FIGURE 2. 
```{r message=FALSE, echo=FALSE}
df <- read_excel("/Users/michaelhuang/Dropbox/University of Chicago/2022 Fall/PLSC 30500/week 2/Karachi and West Pakistan_literature bibliography 1947-61.xlsx")
df[df=="N/A"] <- NA
```

```{r echo=FALSE, warning=FALSE, message=FALSE}
df %>% 
  mutate(Price = as.numeric(Price),
         Page= as.numeric(Page)) %>%
  filter(Year!="1869"&Year!="1930"&Year!="1946"&Year!="1968") %>%
  filter(City == "Karachi" | City == "Lahore" | City =="Hyderabad") %>% 
  group_by(City, Year) %>%
  summarise(Total_price=sum(Price, na.rm = TRUE), Total_page=sum(Page, na.rm = TRUE), Number_of_Books=n()) %>% 
  mutate(Ave_price=Total_price/Number_of_Books, Ave_page=Total_page/Number_of_Books) %>% 
  na.omit() %>% 
  ggplot(
    aes(x=Year, y=Ave_price, size=Number_of_Books))+
      geom_point(aes(col=City)) +
  labs(
    title = "Figure 2. Average Price and Number of Books Published in Hyderabad, Karachi, and Lahore",
    x = "Year",
    y = "Average Price",
    caption = "Source: National Bibliography of Pakistan, 1947-1961"
  ) +
  theme(plot.title = element_text( size = 9))
```

TABLE 1. 
```{r echo=FALSE}
tibble(Variable = c("Price", "Page", "Year", "Urdu", "Fiction"), Obs=c("463","463","463","452","310"), Mean=c("3.966","255.568","1955.577","0.152","0.67"),Std.Dev=c("2.363","135.08","3.85","0.152","0.471"),Min=c("0.4","32","1946","0","0"),Max=c("15","762","1962","1","1")) %>% 
  kable(
    caption = "Summary Statistics",
    col.names = c("Variable", "Obs","Mean","Std.Dev","Min","Max")
  )
```

TABLE 2.
```{r echo=FALSE, message=FALSE, warning=FALSE}
df_sig <- df %>%
  filter(City=="Karachi") %>% 
  mutate(Price = as.numeric(Price),
         Page= as.numeric(Page),
         Year=as.numeric(Year)) %>%
  filter(Year!="1869"&Year!="1930"&Year!="1968") %>% 
  mutate(Fiction=ifelse(Category=="Urdu Fiction"|Category=="Fiction", "1", "0")) %>% 
  mutate(Urdu=ifelse(Language=="U", "1", "0")) %>% 
   mutate(Fiction = as.numeric(Fiction),
         Urdu= as.numeric(Urdu)) %>% 
  select(Urdu, Fiction, Price, Page, Year) %>% 
  na.omit()

within <- plm(Price~Page+Urdu+Fiction, index = "Year", model = "within", data = df_sig)

huxreg(within) %>% set_caption("Regression Table")
```


